name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix:
    name: Nix devshell + Cachix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shell: [py310, py311, py312, py313]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix (Determinate)
        uses: DeterminateSystems/nix-installer-action@main

      - name: Use & (if token) push to Cachix (pybenchx)
        uses: cachix/cachix-action@v16
        with:
          name: pybenchx
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Flake check
        run: nix flake check

      - name: Build with devshell ${{ matrix.shell }}
        run: nix develop .#${{ matrix.shell }} -c uv build

      - name: Test with devshell ${{ matrix.shell }}
        run: nix develop .#${{ matrix.shell }} -c uv run -m pytest -q
